### ISSUE TITLE
[chore] setup the environment for tests

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/reactjs#64]
### С чем связан запрос на фичу?

Необходимо настроить окружения для тестирования

### Расскажите как вы это себе видите

Добавить следующие --dev зависимости в корень проекта :
- jest
- enzyme
- enzyme-adapter-react-16
- ts-jest
- react-dom

Создать файл jest.config.ts для автоматизации запуска тестов с typescript

Изменить в файле package.json в корне проекта скрипт "test" с "mctl test" на "jest"

**Comment by TFK70** [comment]
### После того как добавил конфиг из config репы

##Файл jest.config.ts

```javascript
const inheritedConfig = require('@atlantis-lab/jest-config');

module.exports = inheritedConfig;
```

##Ошибка

$ jest
TypeError: Cannot read property 'rootDir' of undefined
    at readConfigFileAndSetRootDir (/home/darius/Desktop/reactjs/node_modules/@jest/core/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:165:20)
    at readConfig (/home/darius/Desktop/reactjs/node_modules/@jest/core/node_modules/jest-config/build/index.js:217:18)
    at readConfigs (/home/darius/Desktop/reactjs/node_modules/@jest/core/node_modules/jest-config/build/index.js:406:26)
    at runCLI (/home/darius/Desktop/reactjs/node_modules/@jest/core/build/cli/index.js:230:59)
    at Object.run (/home/darius/Desktop/reactjs/node_modules/jest-cli/build/cli/index.js:163:37)
error Command failed with exit code 1.

**Comment by TorinAsakura** [comment]
@TFK70 зачем ты это сюда пишешь? Мне все ошибки за тебя решать? Это часть нашей работы - гугли, решай, тем более ошибка более чем явная

**Comment by TorinAsakura** [comment]
@TFK70 и у тебя маркдаун кривой, после ## должен стоять пробел, посмотри на свои заголовки кривые

**Comment by TorinAsakura** [comment]
@TFK70 и я имел ввиду взять [содержимое конфига](https://github.com/Atlantis-Lab/config/blob/master/packages/jest-config/src/index.ts), а не файл с импортом. Голову включи

**Comment by TFK70** [comment]
@TorinAsakura Решил использовав module.exports и переименовав в jest.config.js

**Comment by TorinAsakura** [comment]
> @TorinAsakura Решил использовав module.exports и переименовав в jest.config.js

скорее костыль, нежели решение, а слабо на TS тоже самое сделать?

**Comment by TFK70** [comment]
@TorinAsakura Окей, сделаю)

**Comment by TFK70** [comment]
@TorinAsakura В общем до него не доходил объект конфига, исправил добавив дефолтный экспорт (файл всё еще .ts)

**Comment by TorinAsakura** [comment]
> @TorinAsakura В общем до него не доходил объект конфига, исправил добавив дефолтный экспорт (файл всё еще .ts)

вместо комментов можно было просто сделать коммит
