### ISSUE TITLE
[bug] latest yarn is broken

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/reactjs#85]
### Описание бага

Последний yarn работает некорректно на этой репе
   
### Воспроизведение
Шаги для воспроизведения бага:

1. Пытаемся установить зависимость в любой из воркспейсов, например:
`yarn workspace @atlantis-lab/next-app-with-emotion add @emotion/react`
2. Видим ошибку

### Ожидаемое поведение
Зависимость должна установиться

### Материалы

Чуть больше подробностей можно получить [здесь](https://github.com/Atlantis-Lab/nextjs/issues/178), т.к. проблемы аналогичны

### Данные окружения
 - Ubuntu@20.04

**Comment by TorinAsakura** [comment]
Проблема локального характера
